### PR TITLE
Updating Link, Issue #72

### PR DESCRIPTION
**Pull request by lunitaire**
Old link led to private video that could not be watched. Updated link to official public video.

### CODE REVIEW

**Comment by jlord** [comment]
Awesome, thank you! :sparkles:

**Comment by rtmunz** [comment]
I have one big Advantage. I have nothing to loose. If I have Talent for this fastforward work. Anyway, would like to keep in touch. Im very carefully and like to make someone a pleasure and lm an impulsiv charaktere with Motivation Skills. Medicine is a thing but Im physically a tougher one. My Name is Raphael and there would be a lot to tell but wie dont know each Otter and so Im looking forward to The Christmas days and if you have overboard I can help you out anytime. If have jet nötig a bi a Imagination of you. The Princess with the dark secret, Im Halluzinating, and wish you a good Night. Rm

**Comment by rtmunz** [comment]
Everything alright, feels a bit, like hope to See you never ....

My offer is guilty and yes, that's it .... until next Time .... ✌

**Comment by rtmunz** [comment]
Im not your secretary nor Club Med Animateur but so on I will not until 4 a clock go to sleep but I Need a reply a Damm your foolish or whatever, writing for myself was and is still boring ...

**Comment by rtmunz** [comment]
If it is allowed ....

**Comment by HelloGitsofthe1** [comment]
Hello you

**Pull request merged**
